// Curated from TheMealDB's free tier: most `strArea` values in list.php?a=list
// return zero recipes on this API key, so this list is only the areas that
// actually have recipes, ordered by recipe count (highest first).
export const AREAS = [
  "British",
  "Spanish",
  "Turkish",
  "Chinese",
  "Jamaican",
  "Polish",
  "Thai",
  "Vietnamese",
  "Canadian",
  "Italian",
  "Australian",
  "Algerian",
  "Saudi Arabian",
  "Japanese",
  "Uruguayan",
  "Croatian",
  "Egyptian",
  "Filipino",
  "Greek",
  "Irish",
  "Malaysian",
  "Portuguese",
  "Tunisian",
  "Russian",
  "Ukrainian",
  "Mexican",
  "Moroccan",
  "Syrian",
  "Kenyan",
]
